### ISSUE TITLE
segment.GNN_seg error

### ISSUE THREAD

**Issue by sudhirkumardubey** [SAMPL-Weizmann/DeepCut#1]
Hello, 

I am trying to replicate your results running the example.ipynb file, but the code shows following error, I have not made any changes to the code still getting this error;

[1](vscode-notebook-cell:/c%3A/Users/Student/Desktop/Sudhir/code/DeepCut-main/DeepCut-main/example.ipynb#W5sZmlsZQ%3D%3D?line=0) stride = 8
      [2](vscode-notebook-cell:/c%3A/Users/Student/Desktop/Sudhir/code/DeepCut-main/DeepCut-main/example.ipynb#W5sZmlsZQ%3D%3D?line=1) device = 'cuda' if torch.cuda.is_available() else 'cpu'
----> [4](vscode-notebook-cell:/c%3A/Users/Student/Desktop/Sudhir/code/DeepCut-main/DeepCut-main/example.ipynb#W5sZmlsZQ%3D%3D?line=3) segment.GNN_seg(mode, epochs, K, pretrained_weights, in_dir, out_dir, save, cc, bs, log_bin, res, facet, layer, stride,
      [5](vscode-notebook-cell:/c%3A/Users/Student/Desktop/Sudhir/code/DeepCut-main/DeepCut-main/example.ipynb#W5sZmlsZQ%3D%3D?line=4)         device)

TypeError: GNN_seg() missing 2 required positional arguments: 'stride' and 'device'

**Comment by sudhirkumardubey** [comment]
I found solution to this this,

in gnn_pool.py replacing

 # x = self.convs(x, edge_index, edge_atrr)  # applying con5v
    x = self.convs(x, edge_index)  # applying con5v

resolves the error as in pyg_nn.GCN, does not need edge_attr. 

Doing this changes, the code runs and gives the output as mentioned in the paper.
Please let me if thats correct way to rectify the changes.

**Comment by xiaolin-coding** [comment]
> I found solution to this this,
> 
> in gnn_pool.py replacing
> 
> # x = self.convs(x, edge_index, edge_atrr) # applying con5v
> ```
> x = self.convs(x, edge_index)  # applying con5v
> ```
> 
> resolves the error as in pyg_nn.GCN, does not need edge_attr.
> 
> Doing this changes, the code runs and gives the output as mentioned in the paper. Please let me if thats correct way to rectify the changes.

I use your solution, but it doesn't work, and still the same error

**Comment by wwzz-max** [comment]
I also use your solution, but it doesn't work, and still the same error
