### ISSUE TITLE
Questions about k-less 

### ISSUE THREAD

**Issue by WheatCao** [SAMPL-Weizmann/DeepCut#4]
Thank you for your inspiring work, but I have some questions regarding “k-less”.

If k is variable, I'm curious how the assignment matrix S mentioned in the paper is estimated with mlp (it looks similar to the diffpooling operation, which requires k to be set artificially). What I found in GNN_pooling.py is a fixed number of "num_clusters". Can you tell me exactly how adaptive clustering is achieved?

Hoping for a reply.

**Comment by amitt1236** [comment]
Hi,
To preform K-less clustering we will chose the "Correlation Clustering" function as our optimization function. 
Once we did it we will still specify a number of clusters K, but this number will be the *max* number of clusters that we allow. 

The "trick" is that the "Correlation Clustering" function enforces the number of clusters, so in some cases the model will not assign patches to some of the K clusters. 

for more information about "correlation clustering" and "normalized cut" optimization you can refer the paper. 

Cheers

**Comment by WheatCao** [comment]
Thank you for answering my questions!
