### ISSUE TITLE
Around reproducing results for VOC-07 

### ISSUE THREAD

**Issue by aryan-at-ul** [SAMPL-Weizmann/DeepCut#5]
Hi, I was trying to replicate the experiment, save the model, and then use the mask generated from the bilateral solver to get the IoU score. When working with the VOC07 dataset, the reported IoU score is 68.8, but when using the same repository, I'm not able to get anywhere close to that score.

I have a few questions: the model is generating one mask per image, but the VOC dataset has segmentation class images with masks for different classes. Should only one class be considered in the experiment, or should I convert the mask to one binary mask and then compute the IoU?

I would appreciate any help related to reproducing this experiment.

**Comment by amitt1236** [comment]
Hi,
The VOC07 dataset experiment, is object localization. The metric is CorLoc. please see the paper for more information. 
We don't use bilateral solver for any of the results in the paper. All results are "as is" model outputs. 

I'm not sure what do you mean by "saving there model" ? We optimize the model for each image, re-init the model weights between images.  At line 55 we save random untrained model weights, and load them before preforming training for each image, please see line 93 at segment.py.

"""
Object Localization Object localization involves identifying the primary object in an image and enclosing it with a bounding box. To perform localization, we follow the steps below: (1) Use our GCN clustering method with k = 2. (2) Examine the edges of the clustered image and identify the cluster that appears on more than two edges as the back- ground, while the other cluster becomes our main object. (3) Apply a bounding box around the identified main ob ject. 
"""
